### ISSUE TITLE
The imported STL model cannot use tools

### ISSUE THREAD

**Issue by wu-yi-hong** [Macad3D/Macad3D#63]
![cc41f131e4ebc6d174d57c8f3605bdb](https://github.com/Macad3D/Macad3D/assets/73647662/daf6f6d6-cce0-44fa-9154-0df7a1e0a99c)

**Comment by dipts** [comment]
This behavior is by design. STL files contain mesh data, and are imported as such. Most modifiers do not work with meshes, but require a solid with BRep data. 

A mesh can be converted into a solid. This enables further processing with all modeling tools, which typically only work on solids. However, this conversion has limitations: The geometric shape itself is not changed. This means that while coplanar triangles are joined together to form a face, "round" structures remain as angular as they were when they were originally tessellated.

The tool is called _Convert to Solid_ and can be found on the ribbon tab _Toolbox_.

See also:
[Topology Model](https://macad3d.net/userguide/html/980d397f-67bc-4874-a24d-42cc80029ef6.htm)
[Converting to Solid](https://macad3d.net/userguide/html/e0d6ed71-f1fa-481b-94b4-c7f76591b1b4.htm#shape-stack-converter)

**Comment by wu-yi-hong** [comment]
> This behavior is by design. STL files contain mesh data, and are imported as such. Most modifiers do not work with meshes, but require a solid with BRep data.
> 
> A mesh can be converted into a solid. This enables further processing with all modeling tools, which typically only work on solids. However, this conversion has limitations: The geometric shape itself is not changed. This means that while coplanar triangles are joined together to form a face, "round" structures remain as angular as they were when they were originally tessellated.
> 
> The tool is called _Convert to Solid_ and can be found on the ribbon tab _Toolbox_.

Thank you very much for your explanation. I will also refer to the source code of the relevant conversion
