### ISSUE TITLE
remove CPU architecture check form installer

### ISSUE THREAD

**Issue by whaslbeck** [Macad3D/Macad3D#70]
Hello,

I tried to install Macad|3D on a M1 Mac in Parallels Desktop, but the installer says:
"This program can only by installed on versions of Windows designed for the follwoing processor architectures: x64" and aborts.

Since Macos brings an x86_64 emulation layer, this warning/error should be removed. Macad runs flawlessly on M1/Parallels once it is installed. (I installed it on a real x86 Windows machine and copied the folder "C:\Program Files\Macad3D" to the mac and everything runs fine!)

BTW: great piece of software!

**Comment by dipts** [comment]
I am very happy to hear that Macad3d works in principle on an M1 Mac under Parallels Desktop. If the setup is (and remains) the only problem, then this should be easy to solve.

Instead of removing the prompt completely, I would issue a warning which can be confirmed. This should ensure that the user knows that there is a hardware incompatibility and confirms that emulation is taking place in some way.
