### ISSUE TITLE
Error When modifying the horizontal coordinate of a vertex of a rectangle in sketch

### ISSUE THREAD

**Issue by liuzhongtu** [Macad3D/Macad3D#76]
When you modify the horizontal coordinate of a vertex of a rectangle to -20 in the sketch, the actual horizontal coordinate after modification is not -20.
<img width="1160" alt="modifyVertex" src="https://github.com/user-attachments/assets/7d81ac0f-a890-4adf-8e47-fda5daa56f05">

**Comment by dipts** [comment]
When creating a rectangle, _Perpendicular_ constraints are automatically added. When the point is moved, these are no longer fulfilled, and the constraint solver now moves all (!) points until the constraints are fulfilled again. 

To assign a fixed horizontal coordinate to the point, you must add a _Horizontal Distance_ constraint to the point, there you can then enter the coordinate. For the solver, now this coordinate has to be retained. Alternatively, you can use the _Fixed_ constraint to retain both coordinates of the point.

If you do not want to work with the constraint system at all, you can simply delete the automatically added constraints after creating the rectangle. Then nobody will ever touch your points again.

**Comment by liuzhongtu** [comment]
In any case, if a variable is set to a certain value, it should not be modified to another value by the software for some reason. 
If the user is fully responsible for the controllability of the software, it will inevitably bring additional learning costs to the user. In other words, to use MACAD, you must understand the basic principles of the 2D geometric constraint engine. Can I understand it this way?

**Comment by liuzhongtu** [comment]
> When creating a rectangle, _Perpendicular_ constraints are automatically added. When the point is moved, these are no longer fulfilled, and the constraint solver now moves all (!) points until the constraints are fulfilled again.
> 
> To assign a fixed horizontal coordinate to the point, you must add a _Horizontal Distance_ constraint to the point, there you can then enter the coordinate. For the solver, now this coordinate has to be retained. Alternatively, you can use the _Fixed_ constraint to retain both coordinates of the point.
> 
> If you do not want to work with the constraint system at all, you can simply delete the automatically added constraints after creating the rectangle. Then nobody will ever touch your points again.

In any case, if a variable is set to a certain value, it should not be modified to another value by the software for some reason. If the user is fully responsible for the controllability of the software, it will inevitably bring additional learning costs to the user. In other words, to use MACAD, you must understand the basic principles of the 2D geometric constraint engine. Can I understand it this way?

**Comment by dipts** [comment]
I understand what you mean. Basically, it is the constraint solver's job to move the points to fulfill the constraints. When you start working with constraints then the input changes from direct point coordinates to indirect requirements. In order to achieve good results overall, this actually means dealing with which requirements are actually important here and then formulating these via constraints. If it is important that a point lies on a certain coordinate, then there is a suitable constraint for this.

Working with constraints is more complex and does not make sense in many cases. The problem probably lies more in the fact that the constraints are set automatically when the rectangle is drawn, without the user having made a conscious decision to use constraints. This is probably the feature that should be reconsidered.

**Comment by liuzhongtu** [comment]
> I understand what you mean. Basically, it is the constraint solver's job to move the points to fulfill the constraints. When you start working with constraints then the input changes from direct point coordinates to indirect requirements. In order to achieve good results overall, this actually means dealing with which requirements are actually important here and then formulating these via constraints. If it is important that a point lies on a certain coordinate, then there is a suitable constraint for this.
> 
> Working with constraints is more complex and does not make sense in many cases. The problem probably lies more in the fact that the constraints are set automatically when the rectangle is drawn, without the user having made a conscious decision to use constraints. This is probably the feature that should be reconsidered.

I agree with you on this point: setting automatic constraints is indeed an issue that needs to be carefully considered. When you draw a rectangle, it should have some automatic constraints, including adjacent segments being perpendicular to each other and the opposite segments being equal in length. Other constraints include whether one pair of segments should be horizontal and the other pair vertical, which is prone to be controversial. 

But when changing the position of one vertex of the rectangle, whether the size of the rectangle should remain unchanged, whether the original angle state of the segment should remain unchanged, and whether the point should be modified according to the user's expected value, I don't think it should be controversial.

**Comment by liuzhongtu** [comment]
> I understand what you mean. Basically, it is the constraint solver's job to move the points to fulfill the constraints. When you start working with constraints then the input changes from direct point coordinates to indirect requirements. In order to achieve good results overall, this actually means dealing with which requirements are actually important here and then formulating these via constraints. If it is important that a point lies on a certain coordinate, then there is a suitable constraint for this.
> 
> Working with constraints is more complex and does not make sense in many cases. The problem probably lies more in the fact that the constraints are set automatically when the rectangle is drawn, without the user having made a conscious decision to use constraints. This is probably the feature that should be reconsidered.

I agree with you on this point: setting automatic constraints is indeed an issue that needs to be carefully considered. When you draw a rectangle, it should have some automatic constraints, including adjacent segments being perpendicular to each other and the opposite segments being equal in length. Other constraints include whether one pair of segments should be horizontal and the other pair vertical, which is prone to be controversial.

But when changing the position of one rectangle, whether the size  and shape of the rectangle should remain unchanged, and whether the position should be modified according to the user's expected value, I don't think it should be controversial.

**Comment by dipts** [comment]
Agreed. Then let's see what we make of it.

I will remove the automatic generation of constraints for the rectangle. Since it is the only tool that automatically generates constraints, even users who want to use constraints will probably not miss it. Especially since - as you have pointed out - there are a lot of ways to constrain a rectangle and the way choosen by the tool may not be the right one for the specific application.

When setting the coordinate of points under constraints, I will have take a look whether it is possible to hold this coordinate for the moment of setting. Although it remains changeable in the further editing process (due to the constraints), it would at least retain the value that was entered for the time being.
